// Modified for LAN Party Hub; see CHANGES.md and NOTICE.md.
export type ControllerLayoutKey =
  | "chaos_kommando_controls"
  | "auction_warehouse"
  | "drawing_guess"
  | "schaetzorama"
  | "word_tiles_board"
  | "single_button"
  | "left_right_hold"
  | "tap_mash"
  | "choice"
  | "card_hand"
  | "secret_card"
  | "dpad"
  | "spell_casting"
  | "racing_controls"
  | "magic_arena"
  | "virtual_joystick"
  | "swipe"
  | "tower_defense"
  | "twin_stick";
